# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanager',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
