# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180307_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('MRP', models.IntegerField()),
                ('batchNum', models.IntegerField()),
                ('batchDate', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=10)),
            ],
        ),
    ]
