# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_inventory_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='productId',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
